# Generated by Django 4.2.8 on 2023-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Aliment',
        ),
    ]
