# Generated by Django 4.2.8 on 2023-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foods_delete_aliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
